version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "49015:80"
    volumes:
      - .:/var/www/electronic
      - ./docker/nginx:/etc/nginx/conf.d
    restart: always
    links:
      - php

  php:
    build: docker
    volumes:
      - .:/var/www/electronic
    restart: always
    links:
      - mysql

  mysql:
    image: mysql:8.4.4
    ports:
      - "49014:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
